
import { SuiWalletProvider } from "@/components/providers/wallet-provider"
import { ConnectButton } from "@/components/connect-button"
import { StatusBar } from "@/components/status-bar"
import type React from "react"
import Link from "next/link"
import type { Metadata } from "next";
// import localFont from "next/font/local";
import { IBM_Plex_Mono} from 'next/font/google'
import "./globals.css";
import Image from "next/image"



const ibm = IBM_Plex_Mono({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin-ext'],
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function NavLink({ href, children }: { href: string; children: React.ReactNode }) {
  // const pathname = usePathname()
  const isActive = false
  return (
    <Link
      href={href}
      className={`top-[2px] px-4 py-2 ${
        isActive ? "bg-white border-t border-l border-r border-gray-200" : "text-gray-600 hover:text-gray-800 border-white border-b z-10 font-bold"
      }`}
    >
      {children}
    </Link>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SuiWalletProvider>
      <body className={`${ibm.className} antialiased font-doto min-h-screen flex flex-col w-full`}>
        
          <header className="border-b bg-gray-100 w-full">
            <div className="px-2 flex items-center justify-between h-full w-full">
              <nav className="flex justify-between w-full items-center">
                <div className="flex items-center gap-2">
                <Image
                  src="/sentient.png"
                  alt="SentientAI"
                  width={32}
                  height={32}
                  className="object-contain h-10"
                />
                <h1 className="text-xl font-">SentientAI</h1>
                </div>
                <div className="flex items-center gap-2">
                <NavLink href="/">Chat</NavLink>
                <NavLink href="/strategies">Strategies</NavLink>
                <NavLink href="/settings">Settings</NavLink>
                </div>
                <ConnectButton />
              </nav>
              
            </div>
          </header>
          <main className="flex-1 h-full py-6 ">{children}</main>
          <StatusBar />
        
      </body>
      </SuiWalletProvider>
    </html>
  )
}

