
import { SuiWalletProvider } from "@/components/providers/wallet-provider"
import { ConnectButton } from "@/components/connect-button"
import { StatusBar } from "@/components/status-bar"
import type React from "react"
import Link from "next/link"
import type { Metadata } from "next";
import localFont from "next/font/local";
import { IBM_Plex_Mono} from 'next/font/google'
import "./globals.css";

const dotoBold = localFont({
  src: "./fonts/Doto_Rounded-Black.ttf",
});

const pixelTimes = localFont({
  src: "./fonts/Pixel-Times.ttf",
});

const ibm = IBM_Plex_Mono({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin-ext'],
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function NavLink({ href, children }: { href: string; children: React.ReactNode }) {
  // const pathname = usePathname()
  const isActive = false
  return (
    <Link
      href={href}
      className={`top-[2px] px-4 py-2 ${
        isActive ? "bg-white border-t border-l border-r border-gray-200" : "text-gray-600 hover:text-gray-800 border-white border-b z-10 font-bold"
      }`}
    >
      {children}
    </Link>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SuiWalletProvider>
      <body className={`${ibm.className} antialiased font-doto min-h-screen flex flex-col w-full`}>
        
          <header className="border-b bg-gray-100 w-full">
            <div className=" flex items-center justify-between h-full w-full">
              <nav className="flex">
                <NavLink href="/">Chat</NavLink>
                <NavLink href="/strategies">Strategies</NavLink>
                <NavLink href="/settings">Settings</NavLink>
              </nav>
              <ConnectButton />
            </div>
          </header>
          <main className="flex-1 h-full py-6 ">{children}</main>
          <StatusBar />
        
      </body>
      </SuiWalletProvider>
    </html>
  )
}

