title: Ethereum Futures Signal Strategy
description: A proprietary trading strategy for Ethereum futures.
baseurl: "/SentientAi"  # Use this if your site is hosted at https://zhoujs93.github.io/SentientAi
url: "https://zhoujs93.github.io"
